### ISSUE TITLE
Lid cutouts not working within display mount area

### ISSUE THREAD

**Issue by FiZiX** [mrWheel/YAPP_Box#112]
Hello, I'm trying to add lid cutouts inside the display mount area, but it doesn't seem to work.

Example:

[UV_Sensor_Mount-v2.scad.txt](https://github.com/user-attachments/files/17906717/UV_Sensor_Mount-v2.scad.txt)

**Comment by rosenhauer** [comment]
Working on a fix.

**Comment by rosenhauer** [comment]
Corrected in 3.3.0
