### ISSUE TITLE
Advice about STP exporting/KiCad?

### ISSUE THREAD

**Issue by cherrydev** [mrWheel/YAPP_Box#13]
I've been designing a PCB with KiCad and I've been finding it handy to make a footprint out of a proposed YAPP box in order to sanity check it and make sure everything's where I think it is. For a 2d footprint, I've found that adding

> projection(cut=true) translate([0,0,-8])

just before the `YAPPgenerate();` will give me a 2d drawing I can export to a DXF and import directly into KiCad. Adjust the z value in order to define what z level to make the projection through.

But what if you want to add a 3d model to the footprint? Well, KiCad requires a STEP file and a WRL file for its 3d models and OpenSCAD doesn't support that. The recommendation I've found for turning an OpenSCAD document into STEP/WRL files is to use FreeCad as an intermediary. I've attempted some simple OpenSCAD example documents in FreeCad and they work fine, but I've pretty much had no luck importing an YAPP model into FreeCad. At best I get a dozen or so primitive objects imported and hundreds of lines of DXF import error messages. I've tried both the built-in OpenSCAD importer and the "Alternate" importer that's a plugin (which claims to support more native OpenSCAD directives). 

Before I throw more time into trying to get this working, I was wondering if anybody had already found a set of import preferences and plugins that work acceptably for this purpose. Thanks!

**Comment by mrWheel** [comment]
This is not an issue.
For questions you can better use my website.

See [this comment](https://willem.aandewiel.nl/index.php/2022/01/02/yet-another-parametric-projectbox-generator/#comment-4399).
