### ISSUE TITLE
How can you set up multiple PCBs at different heights in the same case?

### ISSUE THREAD

**Issue by rosenhauer** [mrWheel/YAPP_Box#14]
I have a project that has a main PCB ("Logic board" with ESP32 and other circuits and connectors) and a display.  

The "Logic board" would be mounted on the base and the Display would be mounted on the cover so the mount points for the "Logic" board' would need to be for example 6mm from the base and the display would need to be 3.5mm from the cover.  Ideally the display would actually be flush with the inside of the cover below an opening on the cover to be able to see/touch it.

**Comment by mrWheel** [comment]
@rosenhauer 

This is not an issue!

The **`YAPPgenerator`** is intended to be used with a simple PCB and not for exotic situations .. although a lot is possible but you have to be creative yourself!

![ESPotifyEcho_Design](https://user-images.githubusercontent.com/5585427/215720530-1a0426c7-de0e-453d-979d-ad002c5d4b6e.gif)
