### ISSUE TITLE
using own variables not possible?

### ISSUE THREAD

**Issue by derFliegendeHamburger** [mrWheel/YAPP_Box#18]
I have come to enjoy YAPP. Now I would like to use own variables for configuration to simplify layout changes; instead of  this:
```

pcbStands = [
                [ 7.5, pcbWidth- 3, standoffHeight, 2, 11, yappBaseOnly, yappPin] , 
                [ pcbLength-7.5, 3, standoffHeight, 2, 11, yappBaseOnly, yappPin] ,
```
I want to write this
```
sx=7.5;
sy=3;
pcbStands = [
                [ sx, pcbWidth- sy, standoffHeight, 2, 11, yappBaseOnly, yappPin] , 
                [ pcbLength-sx, sy, standoffHeight, 2, 11, yappBaseOnly, yappPin] ,
```
you get the idea.
But at compile time the values of own variables are unknown for computing pcbStands. Same for other YAPP declarations.
Please advise how to proceed

**Comment by mrWheel** [comment]
@derFliegendeHamburger 
This is not an issue.
Please post questions at my website
