### ISSUE TITLE
Requst: add snapJoins sample which adds one snap in the middle of each of the 4 edges

### ISSUE THREAD

**Issue by DeflateAwning** [mrWheel/YAPP_Box#55]
The snapJoins use the yappCoordBox default origin. It would be helpful if we could specify the snapjoins relative to the yappCoordPCB origin (via a new arg).

Otherwise, I'm curious to see what the alternative solution is.

**Comment by rosenhauer** [comment]
The following will put a 10mm wide snap joint on all 4 sides.
`
snapJoins   =   
[
  [shellLength/2, 10, yappLeft, yappRight, yappCenter]
  ,[shellWidth/2, 10, yappFront, yappBack, yappCenter]
];
`

![image](https://github.com/mrWheel/YAPP_Box/assets/33765928/a5e207e6-7da7-44d2-9db5-34755133cba9)


Is that what you are looking for?

`

**Comment by DeflateAwning** [comment]
That is it, yeah. Couldn't figure out that `shellLength` was the right number.
