### ISSUE TITLE
Change pin height 

### ISSUE THREAD

**Issue by mrWheel** [mrWheel/YAPP_Box#57]
[Issue](https://willem.aandewiel.nl/index.php/2022/01/02/yet-another-parametric-projectbox-generator/#comment-4760)

[Jonatan Liljedahl](http://kymatica.com/) says:

Is there any way to change the pin height? I want to mount some parts almost flush to the lid, for example a display. But changing the standoff height makes the pin go through the lid.

![image](https://github.com/mrWheel/YAPP_Box/assets/5585427/7e5b4625-c1ec-45d9-9d6e-7f2286f443ac)

**Comment by rosenhauer** [comment]
I can look at adding that with the other change.  I also have a display opening feature 90% complete that I was planning on adding soon.  It allows you to make an opening with a beveled edge and a need pins to attach the display to the lid and snaps to lock it on.  

On my phone now and don't have pictures. But I can share some later.

**Comment by rosenhauer** [comment]
![image](https://github.com/mrWheel/YAPP_Box/assets/33765928/005d80d7-4677-4c20-a223-f7929dec8e06)

This is what I have so far.  It allows you to adjust the pins and the depth from the actual screen to the PCB of the screen.  

Here is a finished box with a screen. 

![PXL_20231219_163515012](https://github.com/mrWheel/YAPP_Box/assets/33765928/075c25b6-690d-4b33-8790-d2e060838a54)
![PXL_20231219_163453159](https://github.com/mrWheel/YAPP_Box/assets/33765928/d88f554b-ecf9-47a7-b898-7bfdf8ac7bcc)


I'm still working on the 3D printing with the new printer. So I ended up hot melt gluing it in as the snaps didn't fit and I was in a hurry.

**Comment by mrWheel** [comment]
Looking good!

**Comment by rosenhauer** [comment]
Fixed the Pin Height/length in #62
