### ISSUE TITLE
p(5) (standoffPinDiameter) of pcbStands is not used

### ISSUE THREAD

**Issue by goramai** [mrWheel/YAPP_Box#59]
configList[5] is used only here in v3.0.1:

  theStandoffPinDiameter = getParamWithDefault(configList[5],standoffPinDiameter);

but theStandoffPinDiameter is not used. I guess some instances of standoffPinDiameter should be replaced with theStandoffPinDiameter.

**Comment by rosenhauer** [comment]
Yes the references to standoffPinDiameter in the sub modules should be theStandoffPinDiameter.  That will let it use it as a default that can be overridden.

**Comment by rosenhauer** [comment]
This was corrected in #60 Multi PCB Option. Pull request.
