### ISSUE TITLE
Enhancement request: threaded inserts support 

### ISSUE THREAD

**Issue by LightTemplar** [mrWheel/YAPP_Box#7]
I would like to have those things as on the image, which can be used for threaded inserts or just as screw hole. On the lid and/or on the base. 
I want to mount box on a bicycle, so I need some reinforcement.
![image](https://user-images.githubusercontent.com/453783/164117299-dabadc7d-0a65-4d65-8fa4-941843bd6004.png)

**Comment by mrWheel** [comment]
General questions and enhancements should be posted as a comment on my website at [this](https://willem.aandewiel.nl/index.php/2022/01/02/yet-another-parametric-projectbox-generator/) post.

**Comment by LightTemplar** [comment]
Those words were here, on GitHub without referencing your Website. If you set your rules, you have to announce them in a place, where they apply. This is a kind of respect to people. Telling them about some rules only then, when they act - it's a clear disrespect.
And if you deal with people without respect, don't expect the respect from them. 
You can do my request or not, it doesn't matter for me anymore.  
![image](https://user-images.githubusercontent.com/453783/164224219-773f5739-8fce-4383-b9a2-423b6734881a.png)
