### ISSUE TITLE
Might be a good time to tag a v3.1 release with all the new features of late?

### ISSUE THREAD

**Issue by DeflateAwning** [mrWheel/YAPP_Box#74]

**Comment by mrWheel** [comment]
Added tag v3.0.1

**Comment by DeflateAwning** [comment]
Awesome, thanks! Just a heads-up that the `YAPPgenerator_v3.scad` says v3.0.2 in it. Not sure there's an easy way to fix it, but next time we do a release, we'll need to update the version in both of those files
