### ISSUE TITLE
lidHookInside in docs is actually hookLidInside, etc

### ISSUE THREAD

**Issue by zyphlar** [mrWheel/YAPP_Box#77]
It seems these functions were recently renamed; need to update docs, readme, blog post, etc

**Comment by mrWheel** [comment]
@zyphlar,

You are right!
But I’m currently very busy with an other project and don’t have the time for at least the next month!

**Comment by zyphlar** [comment]
No problem, would a PR help (is there a repo for the gitbook?)

**Comment by mrWheel** [comment]
This is corrected in the official documentation of the [YAPPgenerator](https://mrwheel-docs.gitbook.io/yappgenerator_en/hooks)!

**Comment by zyphlar** [comment]
Thank you!
