### ISSUE TITLE
BUG: pcbStands only on base, never on lid?

### ISSUE THREAD

**Issue by mrWheel** [mrWheel/YAPP_Box#82]
@rosenhauer 

yappGenerator Version="v3.0.3 (2024-03-21)";

It seems impossible to have a pcbStand on both sides if yoy also use optional params. Base is OK, lid is not. There is a small circle noted on the lid but that does not extend to de PCB.
`
pcbStands = [ [5, 5, yappDefault, yappDefault, 6 + 1.25, 4.1, 9, yappBoth, yappFrontLeft, yappBackRight, yappCoordPCB] ];
`
![standoff](https://github.com/mrWheel/YAPP_Box/assets/5585427/e92e3e3d-d610-490e-9d94-7e3c2ce9d4fa)

With only the parameters the length of the stand on the lid does not comply with the height of the connectors (which are correct)
`
pcbStands = [  [5, 5, yappFrontLeft, yappBackRight] ];
`

# Future request
It would be nice if 

- buttonSlack  = 0.4;

can be set in the box-program.

**Comment by rosenhauer** [comment]
This has a standoffHoleSlack defined as 9.

```
//===================================================================
// *** PCB Supports ***
// Pin and Socket standoffs 
//-------------------------------------------------------------------
//  Default origin =  yappCoordPCB : pcb[0,0,0]
//
//  Parameters:
//   Required:
//    p(0) = posx
//    p(1) = posy
//   Optional:
//    p(2) = Height to bottom of PCB : Default = standoffHeight
//    p(3) = PCB Gap : Default = -1 : Default for yappCoordPCB=pcbThickness, yappCoordBox=0
//    p(4) = standoffDiameter    Default = standoffDiameter;
//    p(5) = standoffPinDiameter Default = standoffPinDiameter;
//    p(6) = standoffHoleSlack   Default = standoffHoleSlack;
//    p(7) = filletRadius (0 = auto size)
//    p(8) = Pin Length : Default = 0 -> PCB Gap + standoff_PinDiameter
//             Indicated length of pin without the half sphere tip. 
//             Example : pcbThickness() only leaves the half sphere tip above the PCB
//    n(a) = { <yappBoth> | yappLidOnly | yappBaseOnly }
//    n(b) = { <yappPin>, yappHole, yappTopPin } 
//             yappPin = Pin on Base and Hole on Lid 
//             yappHole = Hole on Both
//             yappHole = Hole on Base and Pin on Lid
//    n(c) = { yappAllCorners, yappFrontLeft | <yappBackLeft> | yappFrontRight | yappBackRight }
//    n(d) = { <yappCoordPCB> | yappCoordBox | yappCoordBoxInside }
//    n(e) = { yappNoFillet } : Removes the internal and external fillets and the Rounded tip on the pins
//    n(f) = [yappPCBName, "XXX"] : Specify a PCB. Defaults to [yappPCBName, "Main"]
//-------------------------------------------------------------------
pcbStands = 
[
];


```

pcbStands = [ [5, 5, yappDefault, yappDefault, 6 + 1.25, 4.1, 9, yappBoth, yappFrontLeft, yappBackRight, yappCoordPCB] ];

So the hole ends up being the pin size plus the slack (4.1 + 9 = 13.1) which is larger than the stand itself so it vanishes. 

I added to sanity checks to test for this sort of case.  

I'm not sure if you wanted a slack of 0.9 or if you intended the 9 to indicate the length. If that is the case then 2 additional yappDefault parameters need to be added to get it over to p[8] from the current p[6].
