### ISSUE TITLE
Function logic correction

### ISSUE THREAD

**Issue by ron4mac** [mrWheel/YAPP_Box#85]
With a _roundRadius_ of 1.0, the inside of my lid was solid rather than hollowed out. I found that a slight correction to the logic of a function solved the issue.

around line 4876 ... made less than or equal
`function getMinRad(p1, wall) = (p1<=wall) ? 1 : p1 - wall;`

The function probably needs a greater amount of logic where p1==wall.

BTW: really nice work done on a great library

**Comment by rosenhauer** [comment]
Can you share your whole file?  Just setting round radius to 1.0 doesn't get me the same result (non hollow case).

**Comment by ron4mac** [comment]
[sample.scad.txt](https://github.com/mrWheel/YAPP_Box/files/14790391/sample.scad.txt)
(non hollow lid)

**Comment by ron4mac** [comment]
Has not recurred with the latest generator version (2024-03-26) ... even without my modification. 🤷🏼‍♂️

**Comment by ron4mac** [comment]
This issue has reared its head again. Without the modified function above, a lid ridge is not properly formed when the wallThickness is 2.0
[sample.scad.txt](https://github.com/mrWheel/YAPP_Box/files/14897375/sample.scad.txt)

**Comment by rosenhauer** [comment]
Is that with the 3.1 version that was released just a few days ago.

**Comment by ron4mac** [comment]
Yes .. sorry .. 3.1  (as well as 3.05)

**Comment by rosenhauer** [comment]
Traveling right now. I'll look at it again in the next few days and roll in your fix.

**Comment by rosenhauer** [comment]
This has been merged into 3.1.1
