### ISSUE TITLE
Inner radius of connector standoffs/sockets isn't union'd

### ISSUE THREAD

**Issue by zyphlar** [mrWheel/YAPP_Box#87]
When using the connectors feature, some slicers like Prusa or AnkerMake will run "split to objects/parts" to separate out parts for printing, but the radius'd rings inside the connectors will drop to the bed instead of staying merged with the bottom of the case.

Theoretically exporting them all as one mesh would help with this, though I'm not deep into YAPP enough to know the details. I just know this is the only feature I encounter this issue with. Cura and MatterControl don't seem to have this problem either.

**Comment by rosenhauer** [comment]
I only use Cura but will check out this issue.

**Comment by rosenhauer** [comment]
This was corrected in 3.1.0
